version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=mongo
    networks:
      - nw
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - nw
networks:
  nw:
